# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Build

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: publish
    - uses: actions/upload-artifact@v2
      with:
        path: ./polo-bukkit/build/libs/polo-bukkit-*.jar
